"""
Export utilities for EconoPulse.
Provides CSV (and basic text-report) export helpers.
"""

import io
from typing import Optional

import pandas as pd


def to_csv_bytes(df: pd.DataFrame) -> bytes:
    """Serialise a DataFrame to UTF-8 CSV bytes."""
    buffer = io.StringIO()
    df.to_csv(buffer, index=False)
    return buffer.getvalue().encode("utf-8")


def generate_text_report(
    indicators_df: pd.DataFrame,
    alerts_df: pd.DataFrame,
    selected_countries: list[str],
    selected_year_range: tuple[int, int],
) -> str:
    """Generate a plain-text narrative summary report."""
    start_year, end_year = selected_year_range
    lines = [
        "=" * 60,
        "  EconoPulse — Economic Indicators Report",
        f"  Period: {start_year} – {end_year}",
        f"  Countries: {', '.join(selected_countries)}",
        "=" * 60,
        "",
    ]

    from data.sample_data import INDICATORS  # local import to avoid circular deps

    for country in selected_countries:
        lines.append(f"## {country}")
        country_df = indicators_df[
            (indicators_df["country"] == country)
            & (indicators_df["year"].between(start_year, end_year))
        ]
        for code, name in INDICATORS.items():
            subset = country_df[country_df["indicator_code"] == code]
            if subset.empty:
                continue
            latest = subset.loc[subset["year"].idxmax()]
            earliest = subset.loc[subset["year"].idxmin()]
            change = latest["value"] - earliest["value"]
            lines.append(
                f"  {name}:"
                f" {latest['value']:.2f} in {int(latest['year'])}"
                f" (change from {int(earliest['year'])}: {change:+.2f})"
            )
        lines.append("")

    if not alerts_df.empty:
        country_alerts = alerts_df[alerts_df["country"].isin(selected_countries)]
        if not country_alerts.empty:
            lines.append("## Stress Signals Detected")
            for _, row in country_alerts.sort_values(["country", "year"]).iterrows():
                lines.append(
                    f"  [{row['severity'].upper()}] {row['country']} ({row['year']}): "
                    f"{row['signal_type']}"
                )
            lines.append("")

    lines.append("=" * 60)
    lines.append("Report generated by EconoPulse.")
    return "\n".join(lines)
